#!/bin/bash

PID="-1"
ARGS=("$@") 
MONITOR_FILES_EXPR=${ARGS[0]}

if [[ -z $(which inotifywait) ]]; then
  echo "Installing inotify-tools..."
  sudo apt-get update
  sudo apt-get install -y inotify-tools
fi

action() {
  command=
  [[ $PID != "-1" ]] && kill -9 $PID 2>/dev/null;
  SCRIPTS_AFTER_SECOND=("${ARGS[*]:1}")
  for script in $SCRIPTS_AFTER_SECOND; do
    command="$command $script"
  done

  echo "$command" | bash &

  PID=$!;
}

firstAction() {
  action
}

loopActions() {
  action
}

firstAction

while echo "inotifywait -qqre modify $MONITOR_FILES_EXPR" | bash; do
  loopActions
done